import { RegPilotData } from '@src/interface';
import { nanoid } from 'nanoid';

export const DEFAULT_PILOT: RegPilotData = {
            name: "New Pilot",
            active_mech: null,
            background: "",
            callsign: "",
            campaign: "",
            cc_ver: "",
            cloudID: "",
            cloudOwnerID: "",
            cloud_portrait: "",
            core_bonuses: [],
            current_hp: 0,
            custom_counters: [],
            faction: null,
            group: "",
            history: "",
            id: nanoid(),
            lastCloudUpdate: "",
            level: 0,
            loadout: {
                id: nanoid(),
                name: "Foundry Loadout",
                armor: [null],
                gear: [null, null, null],
                weapons: [null, null],
                extendedGear: [null, null],
                extendedWeapons: [null],
            },
            mechSkills: [0,0,0,0],
            mechs: [],
            mounted: false,
            notes: "",
            organizations: [],
            owned_armor: [],
            owned_gear: [],
            owned_weapons: [],
            player_name: "",
            portrait: "",
            quirk: null,
            skills: [],
            sort_index: 0,
            status: "",
            talents: [],
            text_appearance: ""
        }